site_name: django-tree-perm 树结点管理
repo_url: https://github.com/SkylerHu/django-tree-perm
docs_dir: .
exclude_docs: |
  frontend/*
  */node_modules/*

theme:
  name: readthedocs
  language: zh

nav:
  - 首页: README.md
  - 数据库Model: docs/ModelDoc.md
  - 接口API: docs/API.md
  - 工具类: docs/Utils.md
  - Release Notes: docs/CHANGELOG-1.x.md
  - 贡献者指南: docs/CONTRIBUTING.md

plugins:
  - same-dir
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [django_tree_perm]
          options:
            heading_level: 3
            show_root_heading: true
            show_symbol_type_heading: true
            show_source: false
          selection:
            docstring_style: google
