# Generated by Django 4.2.16 on 2024-09-21 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-b][a-b0-9_-]{1,63}$",
                                message="字母开头, 由小写字母、数字、中横线、下划线组成，长度范围为2~64个字符",
                            )
                        ],
                        verbose_name="唯一标识",
                    ),
                ),
                ("disabled", models.BooleanField(db_index=True, default=False, verbose_name="是否禁用")),
            ],
            options={
                "verbose_name": "叶子结点",
            },
        ),
        migrations.CreateModel(
            name="PermRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-b][a-b0-9_-]{1,63}$",
                                message="字母开头, 由小写字母、数字、中横线、下划线组成，长度范围为2~64个字符",
                            )
                        ],
                        verbose_name="唯一标识",
                    ),
                ),
                ("alias", models.CharField(max_length=128, verbose_name="显示名称")),
                ("description", models.CharField(default="", max_length=1024, verbose_name="描述")),
            ],
            options={
                "verbose_name": "角色",
            },
        ),
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-b][a-b0-9_-]{1,63}$",
                                message="字母开头, 由小写字母、数字、中横线、下划线组成，长度范围为2~64个字符",
                            )
                        ],
                        verbose_name="唯一标识",
                    ),
                ),
                ("alias", models.CharField(max_length=128, verbose_name="显示名称")),
                ("description", models.CharField(default="", max_length=1024, verbose_name="描述")),
                ("depth", models.SmallIntegerField(default=1, verbose_name="深度")),
                (
                    "path",
                    models.CharField(db_index=True, default="", max_length=191, unique=True, verbose_name="全路径"),
                ),
                (
                    "leaf",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="node",
                        to="django_tree_perm.leafnode",
                        verbose_name="叶子结点",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="django_tree_perm.treenode",
                        verbose_name="父类结点",
                    ),
                ),
            ],
            options={
                "verbose_name": "树结点",
                "ordering": ("path",),
            },
        ),
        migrations.CreateModel(
            name="NodeRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_set",
                        to="django_tree_perm.treenode",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_set",
                        to="django_tree_perm.permrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_role_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "结点角色关系",
                "unique_together": {("node", "role", "user")},
            },
        ),
    ]
