name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd frontend && npm install . && cd ../

      - uses: pre-commit/action@v3.0.1
