name: test for py3

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'example_project/**'
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'example_project/**'
      - 'frontend/**'
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox and any other packages
        run: pip install tox coveralls

      - name: Run tox targets for ${{ matrix.python }}
        run: |
          pyFlag=$(echo ${{ matrix.python }} | tr -d .)
          for e in `tox -l | grep "$pyFlag-" | grep -v lint`; do tox -e $e; done
